var income1 = {
    wageIncome: 70970.00,
    outOfStateInterest: 0,
    maInterest: 0,
    interest: 0,
    propertyTax: 3254,
    mortgageInterest: 8000,
    mortgageInsurance: 0,
    otherHousehold: 4000,
    charity: 0,
    dependentCareFsa: 0,
    type: 'hoh',
    numDependents: 2,
    childCare: 16430,
    rent: 0,
    undergraduateStudentLoanInterest: 0,
    shortTermCapitalGains: 0,
    longTermCapitalGains: 0,
    ordinaryDividends: 0,
    qualifiedDividends: 0,
    stateTaxWithheld: 3052.00,
    previousStateTaxPayment: 0,
    commute: 0
};

var income2 = {
    wageIncome: 35485.00,
    outOfStateInterest: 0,
    maInterest: 0,
    interest: 0,
    propertyTax: 0,
    mortgageInterest: 0,
    mortgageInsurance: 0,
    otherHousehold: 0,
    charity: 0,
    dependentCareFsa: 0,
    type: 'single',
    numDependents: 0,
    childCare: 0,
    rent: 0,
    undergraduateStudentLoanInterest: 0,
    shortTermCapitalGains: 0,
    longTermCapitalGains: 0,
    ordinaryDividends: 0,
    qualifiedDividends: 0,
    stateTaxWithheld: 1526.00,
    previousStateTaxPayment: 0,
    commute: 0
};